import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import { ThemeProvider } from "@/providers/theme-provider";
import { ReactQueryProvider } from "@/providers/reactQueryProvider";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type NewType = {
  children: React.ReactNode;
};

export default function RootLayout({
  children,
}: Readonly<NewType>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <ClerkProvider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <ReactQueryProvider>
              {children}
            </ReactQueryProvider>
          </ThemeProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}